name: webservices
channels:
  - conda-forge
platforms:
  - linux-64
dependencies:
  - anaconda-client >=1.8.0
  - cachetools
  - conda
  - conda-build
  - conda-forge-metadata >=0.9.2
  - conda-forge-pinning
  - conda-forge-tick >=2025.1.51
  - conda-forge-feedstock-ops >=0.10.1  # pin to fix bug in rerenders
  - conda-recipe-manager
  - conda-smithy >=3.34.1  # this pin is for jinja2 sandboxes
  - conda-souschef
  - cryptography >=39
  - python-dateutil
  - git
  - gitpython
  - lxml
  - mock
  - parameterized
  - pip
  - pygithub >=2.2.0,<2.6.0  # lower bound for GH App endpoints and upper bound so making app tokens works
  - python =3.11.*
  - pytz
  - pyyaml
  - rattler-build >=0.35.4
  - requests
  - ruamel.yaml >=0.16
  - ruamel.yaml.jinja2
  - setuptools
  - setuptools_scm >=8
  - shellcheck
  - tini
  - tornado
  - tqdm
  # dev dependencies
  - pytest <8.2.0
